### ISSUE TITLE
EV3 suports only .NET4.0

### ISSUE THREAD

**Issue by budougumi0617** [budougumi0617/MonoBrickFirmwareWrapper#12]
We cannot use `Task.Run` etc on EV3... :sob:

**Comment by Geroshabu** [comment]
そういえばロボコンの時に `public int X { get; set; } = 10;` という書き方ができずに泣いた覚えがある.

**Comment by budougumi0617** [comment]
Set v4.0 to TargetFrameworkVersion...

**Comment by budougumi0617** [comment]
Need more setting to compile version.
Maybe, MonoBrickFirmware executes only on Mono2.X.
Mono2.X supports C#4.0.
```
Firmware 1.2.0.39486
Mono version 2.10.9
Mono CLR v4.0.30.319
```

Reference URL
http://www.moonmile.net/blog/archives/7457
https://en.wikipedia.org/wiki/Mono_%28software%29
